#!/bin/bash
universe= vanilla
output= output.txt
error= errors.txt
request_cpus = 1
should_transfer_files=yes
when_to_transfer_output=on_exit
transfer_input_files=simulation.input
log= logfile
executable=/scratch365/eosaro/Research/Diffusivities/Mixtures/PXT/CuBTC/PPP/TTT/MMM/raspa.sh
queue
